### ISSUE TITLE
Confidence limits on the probability plot

### ISSUE THREAD

**Issue by Charlesoxmt** [slightlynybbled/weibull#11]
Request that confidence lines are plotted on the probability plot, please.

**Comment by slightlynybbled** [comment]
Agreed.  I have been wanting this as well, just haven't had as much time to dedicate to the project.  Will have a look at it again now that I know someone else is interested.

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
