### ISSUE TITLE
Weibayes issue with failures

### ISSUE THREAD

**Issue by RyanFunk021** [slightlynybbled/weibull#13]
Line 728:
I believe the code is correct when no failures exist:
`etaseries[0, :] = ((self.data ** self.beta) / self.r)`

but when failures exist, it should be:
`etaseries[0, :] = ((self.data ** self.beta) / NumberOfFailures)`

also, if 63% confidence is acceptable, and no failures exist, self.r = 1 would be functionally correct.

ref:
http://www.dtic.mil/dtic/tr/fulltext/u2/a143100.pdf
https://www.aesseal.com/sites/aesseal.com/files/whitepaper/WP-LABTECTALIFE-01.pdf

**Comment by slightlynybbled** [comment]
I appreciate the feedback.  When I get to this project again, I will definitely make the change.  Thank you!

**Comment by djhak9** [comment]
hi!
this is Dj,
in weibull_text_Example.py(The example in the book Weibull Analysis by Bryan Dodson)
every thing is ok, for small data points, but in case of large Data, for example 1000 etc..
for all the suspended points, did we have to type  that many time type 0 or False, is their any other way

_fail_times = [
    42.1, 105.9, 151.3, 195.6,
    77.8, 117.0, 157.3, 207.0,
    83.3, 126.9, 163.8, 215.3,
    88.7, 138.7, 177.2, 217.4,
    101.8, 148.9, 194.3, 258.8
]

suspensions = [1, 0, 1, 1,
               0, 0, 0, 0,
               1, 0, 0, 1,
               1, 0, 1, 0,
               0, 0, 1, 1]_

**Comment by RyanFunk021** [comment]
I don't know that particular example, but if you create a list of indexes
for the true values, then you could use a for loop to create a list with
1/0 in the necessary places (if I understand your intent)

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
