### ISSUE TITLE
One-Sided Confidence Intervalls for MLE and Linear Regression

### ISSUE THREAD

**Issue by dnns92** [slightlynybbled/weibull#14]
It would be very nice to add the option of one-sided confidence intervalls for maximum likelihood and linear regression estimators. This is very widely used in field data analysis to ensure you're staying under a certain level of failures with e.g. 90%

Cheers,
Dennis

**Comment by slightlynybbled** [comment]
I totally agree!  When I wrote this, it was for a particular purpose and served the needs of a particular organization.  At this time, I don't have the resources to dedicate to another effort, but I welcome pull requests!

**Comment by dnns92** [comment]
Hey,
thanks for your answer. 
I could potentially add the feature myself. However in the code considering the confidence limits you say that the idea is taken from Brian Dodson's book on page 54. Is there also an algorithm for one-sided intervalls written in there? 
I mean I understand the fisher matrix, but as efficitent implementation should be a factor It would be nice to have some pseudo-code or something similar.
