### ISSUE TITLE
Bug: MLE fails regulary on low data scope (<4)

### ISSUE THREAD

**Issue by dnns92** [slightlynybbled/weibull#15]
Hey, 
I wanted to illustrate how bad the estimation with MLE /Linear Regression can get using only 1-5 tests. Therefore I had a script that does an MLE on 2-5 randomly generated datapoints 100 times. It appears a LinAlgError("Singluar Matrix" ) in irregular intervals when using less than 4 datapoints. 

It also seems to be connected to the calculation of the confidence level that is chosen.

Do you know how that happens? I could potentially fix the bug myself, but I do have limited understanding of your code and any insight from your side would be very appreciated.

This is the full error message I get:

runfile('//imapc/benutzer/Mitarbeiterdaten/huegle/04_Projekte/04_Datenumfang_Feldanalyse/01_Skripte/MLE_vs_Regression.py', wdir='//imapc/benutzer/Mitarbeiterdaten/huegle/04_Projekte/04_Datenumfang_Feldanalyse/01_Skripte')
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 2 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 3 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 4 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 2 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 3 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 4 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 2 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 3 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 4 data points
WARNING:weibull.weibull:the linear regression method is likely to yield better results with 2 data points
C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\weibull\weibull.py:151: RuntimeWarning: overflow encountered in double_scalars
  shape = shape + (a + (1.0 / shape) - (c / b)) / ((1.0 / shape ** 2) + ((b * h) - c ** 2) / b ** 2)
C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\weibull\weibull.py:151: RuntimeWarning: invalid value encountered in double_scalars
  shape = shape + (a + (1.0 / shape) - (c / b)) / ((1.0 / shape ** 2) + ((b * h) - c ** 2) / b ** 2)
Traceback (most recent call last):

  File "<ipython-input-1-e6db56977266>", line 1, in <module>
    runfile('//imapc/benutzer/Mitarbeiterdaten/huegle/04_Projekte/04_Datenumfang_Feldanalyse/01_Skripte/MLE_vs_Regression.py', wdir='//imapc/benutzer/Mitarbeiterdaten/huegle/04_Projekte/04_Datenumfang_Feldanalyse/01_Skripte')

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "//imapc/benutzer/Mitarbeiterdaten/huegle/04_Projekte/04_Datenumfang_Feldanalyse/01_Skripte/MLE_vs_Regression.py", line 47, in <module>
    an.fit(method = 'mle')

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\weibull\weibull.py", line 263, in fit
    self._confidence(confidence_level)

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\weibull\weibull.py", line 216, in _confidence
    fprime = np.linalg.inv(f)

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 528, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)

  File "C:\Users\huegle\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix

**Comment by slightlynybbled** [comment]
Could you provide your full script?  I can't repeat the symptoms without knowing what the inputs are.

**Comment by dnns92** [comment]
I found out what causes the error and I already have a simple fix for it. As im in parallel programming my own weibull analysis tool, i can also validate that this fixes the error permanantly:
Usually the likelihood function is quite steep. A newton raphson will therefore find the root near to the real root quickly. However if the likelihood function is very flat, the first estimation of the newton raphson can be below 0. If this happens, there will be no comeback over the zero-asymptote and the newton raphson will find a root below zero. You can easily overcome this problem by instead of calculating the shape parameter by using the following code:
for i in range(1, 11):
            a = np.sum(np.log(dtf_failed) * 1.0) / dtf_failed.size
            b = np.sum(dtf_all ** shape)
            c = np.sum((dtf_all ** shape) * np.log(dtf_all))
            h = np.sum((dtf_all ** shape) * (np.log(dtf_all)) ** 2)
            shape = shape + (a + (1.0 / shape) - (c / b)) / ((1.0 / shape ** 2) + ((b * h) - c ** 2) / b ** 2)
            shape = max(shape, 0.05)

which will limit the estimation of the newton raphson to 0.05 as the lowest possible value. Values like this,(very near zero) have no physical meaning anymore, which makes this a sound approach.

**Comment by slightlynybbled** [comment]
I believe that I fixed the issue in v0.1.1
