### ISSUE TITLE
suspened data not considered in MLE

### ISSUE THREAD

**Issue by hisokar722** [slightlynybbled/weibull#16]
sorry about that.  i did not read it carefully

**Comment by dnns92** [comment]
Hey Hisokar,
Right censores data is considered in the current code. The results of the MLE have been validated with minitab by myself. 
If you need additional help with the code, please provide more info or ask a more precise question.

**Comment by hisokar722** [comment]
For the confidence bounds of parameter estimation, which approach is used ?   fisher matrix, likelihood ratio, bayesian or others ?

**Comment by slightlynybbled** [comment]
Fisher matrix.
