### ISSUE TITLE
Likelihood of new data points under a fitted model

### ISSUE THREAD

**Issue by AruniRC** [slightlynybbled/weibull#21]
After fitting a Weibull model to some data, what if I want to see the probability of a new datapoint belonging to this distribution, i.e. the usual likelihood of a data point under a model? I could find no example of this (or perhaps the wording is different, in which case an explanatory note in the docs would be really great!)

**Comment by slightlynybbled** [comment]
I'm not sure what you are looking for with your question.  Perhaps I simply don't have the vocabulary to understand what you are asking.  As I understand it, the weibull model probability plot line shows the next most likely failures based on known past data.

Could you clarify the question or, perhaps, even submit a pull request implementing what you are asking for?

**Comment by AruniRC** [comment]
Sure, let me try to explain another way (apologies if differing terminology is causing a confusion)

Consider the following probability density function (PDF) for the Weibull distribution, where k = beta and lambda = eta to be consistent with the notation used in your docs. Suppose the scale and shape params (beta, eta) are given.

![image](https://user-images.githubusercontent.com/1054799/61345410-e021e300-a809-11e9-8108-4f8b64b407a3.png)

Given a new data point, i.e. a specific value of `x`, what is the value of the p.d.f. `f` ? In other words, what is the likelihood that a data point `x` comes from a specified Weibull distbution (beta, eta) or (k, lambda)?

A direct SciPy version of what I am wondering about can be found in the following links:

1. PDF for a distribution: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.pdf.html#scipy.stats.rv_continuous.pdf
2. The SciPy `expweib` class which implements such a PDF method: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.exponweib.html

**Comment by slightlynybbled** [comment]
To get a plot of the PDF, you can use the `pdf()` function of the `Analysis` class:

    analysis = Analysis(<add your data here>)
    analysis.fit()
    analysis.pdf()

I don't provide any direct pdf data, but you could find it easily enough:

    x = np.linspace(0.01, analysis.eta*5, 1000)
    y = scipy.stats.weibull_min.pdf(x, analysis.beta, 0, self.eta)

Perhaps the `pdf()` method - and other plot methods - could return the (x, y) data that generated the plot?  Would that be helpful?

**Comment by AruniRC** [comment]
I think the workaround you provided in the second snippet (calling the scipy `weibull_min` with parameters estimated by your Analysis class) is good enough. Since evaluating the likelihood under a PDF (which is what scipy does) is quite different from visualizing the PDF (which is what your method does), perhaps there is no sense in pursuing this IMO.

**Comment by slightlynybbled** [comment]
This code snippet was taken from the code... perhaps if the `analysis.pdf()` method returned `x`, and `y`?

**Comment by AruniRC** [comment]
It might be neater to have a separate method `analysis.likelihood(x)` that returns the value of the PDF associated with the Analysis object at `x`.

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
