### ISSUE TITLE
right-censored-data error

### ISSUE THREAD

**Issue by faceany** [slightlynybbled/weibull#23]
`# -*- coding: UTF-8 –*-
import weibull
data6 = [1, 2, 3, 4, 5]
dataSus6 = [False,False,False,False,False]
for i in range(100):
    data6.append(6)
    dataSus6.append(True)

weibullModel = weibull.Analysis(data6,dataSus6,0.95)
weibullModel.fit("mle")
print(weibullModel.beta)
print(weibullModel.eta)

weibullModel.cdf()
`
error info :

E:\python374\lib\site-packages\weibull\weibull.py:169: RuntimeWarning: overflow encountered in double_scalars
  shape = shape + (a + (1.0 / shape) - (c / b)) / ((1.0 / shape ** 2) + ((b * h) - c ** 2) / b ** 2)
E:\python374\lib\site-packages\weibull\weibull.py:169: RuntimeWarning: invalid value encountered in double_scalars
  shape = shape + (a + (1.0 / shape) - (c / b)) / ((1.0 / shape ** 2) + ((b * h) - c ** 2) / b ** 2)
Traceback (most recent call last):
  File "E:/pythonprj/TestWeb.py", line 71, in <module>
    weibullModel.fit("mle")
  File "E:\python374\lib\site-packages\weibull\weibull.py", line 282, in fit
    self._confidence(confidence_level)
  File "E:\python374\lib\site-packages\weibull\weibull.py", line 235, in _confidence
    fprime = np.linalg.inv(f)
  File "<__array_function__ internals>", line 6, in inv
  File "E:\python374\lib\site-packages\numpy\linalg\linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "E:\python374\lib\site-packages\numpy\linalg\linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

**Comment by parthshah1993** [comment]
I am getting similar error. @slightlynybbled  can you have a look?

**Comment by slightlynybbled** [comment]
Please see the [`reliability`](https://reliability.readthedocs.io/en/latest/) package for a more feature-rich experience.  I am shifting my work over to that package and will consider the `weibull` package obsolete.
